name: manga-shelf
services:
  mangashelf:
    image: ${DOCKER_REGISTRY}manga-shelf-ui:latest
    container_name: mangashelf
    ports:
      - 5299:8080
    networks: 
      - manga-network
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        ASPNETCORE_HTTP_PORTS: 8080
        ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    env_file:
      - .env
    volumes:
      - images:/app/wwwroot/images:rw
    restart: always
    depends_on:
      mangashelf.db:
        condition: service_healthy

  mangashelf.parser:
    container_name: mangashelf.parser
    image: ${DOCKER_REGISTRY}manga-shelf-parser:latest
    networks: 
      - manga-network
    environment:
      DOTNET_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    volumes:
      - images:/app/wwwroot/images:rw
    env_file:
      - .env
    restart: always
    depends_on:
        mangashelf:
            condition: service_started

  mangashelf.db:
    container_name: mangashelf.db
    image: mysql:8.0
    ports:
      - 3303:3306
    networks:
      - manga-network
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MANGA_HOST}
      MYSQL_ROOT_PASSWORD: ${MANGA_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

networks:
  manga-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  images:
    driver: local
  accdata:
    driver: local

